# Generated by Django 6.0.4 on 2026-05-04 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('school_name', models.CharField(max_length=200)),
                ('level_of_study', models.CharField(choices=[('HND 1', 'HND 1'), ('HND 2', 'HND 2'), ('Bachelor Year 1', 'Bachelor Year 1'), ('Bachelor Year 2', 'Bachelor Year 2'), ('Bachelor Year 3', 'Bachelor Year 3'), ('Master Year 1', 'Master Year 1'), ('Master Year 2', 'Master Year 2'), ('PhD', 'PhD')], max_length=100)),
                ('field_of_study', models.CharField(max_length=150)),
                ('internship_domain', models.CharField(choices=[('Software Development', 'Software Development'), ('Web Development', 'Web Development'), ('Data Analytics', 'Data Analytics'), ('Cybersecurity', 'Cybersecurity'), ('Graphic Design', 'Graphic Design'), ('Digital Marketing', 'Digital Marketing'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Networking', 'Networking')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('cv', models.FileField(upload_to='documents/cv/')),
                ('recommendation_letter', models.FileField(upload_to='documents/recommendations/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_applied'],
            },
        ),
    ]
